name: Update Job List

on:
  schedule:
    # ירוץ בכל יום בשעה 08:00 בבוקר (שעון UTC)
    - cron: '0 8 * * *'
  workflow_dispatch: # מאפשר לך להריץ ידנית מתי שבא לך בלחיצת כפתור בגיטהאב

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # שדרוג קל לגרסת פייתון יציבה ומודרנית
          cache: 'pip' # מאיץ את ההרצות הבאות על ידי שמירת הספריות בזיכרון מטמון

      - name: Install dependencies
        run: pip install -r requirements.txt

      # שלב חובה עבור הסריקה של האתרים העצמאיים (Custom)
      - name: Install Playwright Browsers
        run: python -m playwright install --with-deps chromium

      - name: Run scraping script
        run: python scrape_jobs.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated job list automatically"
          file_pattern: README.md
